### ISSUE TITLE
difference with beyondcode/laravel-credentials

### ISSUE THREAD

**Issue by matijakovacevic** [Harmonic/laravel-envcoder#2]
could you tell me what is the difference between your package and
https://github.com/beyondcode/laravel-credentials ?

Thanks.

**Comment by craigharman** [comment]
Sure. The 2 major differences are:

1) Your .env is still kept locally unencrypted so you can edit it as normal. You don't need to run a special artisan command to make changes to your .env file everytime you want to make a change.

2) You don't need to change your Laravel app's code (eg. using the credentials function to retrieve encrypted credentials in the case of the beyond code solution).  env() still works.

Hope that helps!

**Comment by matijakovacevic** [comment]
Thank you for the explanation :+1: 

Btw, will the possibility of encrypting multiple .env files be added?

For situations where you have production and sandbox environment, so 2 branches containing each own ENV file.

**Comment by craigharman** [comment]
Yes, I have been thinking about adding this. How would you see this working?

Ie. encypting and decrypting a specific .env file from the command line: 
```artisan env:encrypt .staging.env```

Auto encrypting of all .env files?

Happy to hear how you would use it and we can look into a solution.

**Comment by craigharman** [comment]
#4 Added in v1.0.3
