### ISSUE TITLE
is this using GnuPg for encryption under the hood?

### ISSUE THREAD

**Issue by codeitlikemiley** [Harmonic/laravel-envcoder#5]

**Comment by craigharman** [comment]
We use the defuse/php-encryption package, details available here: https://github.com/defuse/php-encryption

and more on the cryptography behind it all here: https://github.com/defuse/php-encryption/blob/master/docs/CryptoDetails.md

Hope that helps, let me know if you need any further assistance or have suggestions for improvements.
