### ISSUE TITLE
Problem with variables with spaces

### ISSUE THREAD

**Issue by chrisrollins65** [Harmonic/laravel-envcoder#9]
I have a couple variables in my .env that have multiple words with spaces. This is handled by putting the variables in quotes.
But I've noticed that upon decrypting the .env.enc with envcoder, the quotes are gone and the .env becomes invalid.

For example, the following variable:
`MAIL_FROM_NAME="My name"`
is decrypted as:
`MAIL_FROM_NAME=My name`
resulting in the error:
`Failed to parse dotenv file due to unexpected whitespace.`

**Comment by craigharman** [comment]
Resolved in
https://github.com/Harmonic/laravel-envcoder/releases/tag/1.0.6
